run:
  timeout: 5m
  allow-parallel-runners: true

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gochecknoglobals
        - dupl
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false

linters:
  disable-all: true
  enable:
    - dupl
    - errcheck
    - exportloopref
    - ginkgolinter
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused

linters-settings:
  lll:
    line-length: 200
  gocyclo:
    min-complexity: 20
  revive:
    rules:
      - name: comment-spacings
