name: Build binary

on:
  pull_request:
    paths:
    - "api/**"
    - "cmd/main.go"
    - "graphql/**"
    - "internal/**"

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - id: vars
      run: |
        echo "go_version=$(cat go.mod | head -3 | tail -1 | cut -d ' ' -f 2)" >> $GITHUB_OUTPUT
        echo "Using Go version ${{ steps.vars.outputs.go_version }}"

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ steps.vars.outputs.go_version }}

    - name: Build
      run: go build cmd/main.go
