name: Labelling pull request

on:
  pull_request:

jobs:
  golangci:
    name: Verify lint
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        version: [1.24]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.version }}
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.5

  check-labels:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      issues: write
      pull-requests: write
      statuses: write

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.DEPLOY_APP_ID }}
          private-key: ${{ secrets.DEPLOY_APP_KEY }}

      # https://github.com/fuxingloh/multi-labeler
      - name: labels
        uses: fuxingloh/multi-labeler@v4
        with:
          github-token: ${{ steps.app-token.outputs.token }}
