name: Publish Brew release

on:
  push:
    tags:
      - "*"

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Documentation here
      # https://github.com/mislav/bump-homebrew-formula-action?tab=readme-ov-file#action-inputs
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          commit-message: "feat({{formulaName}}): publish version {{version}} 🤖"
          formula-path: ssh-list.rb
          homebrew-tap: Tchoupinax/homebrew-brew
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
